package nl.fews.archivedatabase.mongodb.shared.enums;

/**
 *
 */
public enum TimeSeriesType {
	SCALAR_EXTERNAL_HISTORICAL,
	SCALAR_EXTERNAL_FORECASTING,
	SCALAR_SIMULATED_FORECASTING,
	SCALAR_SIMULATED_HISTORICAL,
	SCALAR_EXTERNAL_HISTORICAL_BUCKET,
	SCALAR_SIMULATED_HISTORICAL_STITCHED,
	SCALAR_SIMULATED_FORECASTING_OVERWRITE,
	SCALAR_SIMULATED_HISTORICAL_OVERWRITE,
	GRID_EXTERNAL_HISTORICAL,
	GRID_EXTERNAL_FORECASTING,
	RATING_CURVES,
	CONFIGURATION,
	PRODUCTS
}
