db.BucketSize.createIndexes(
{"bucketCollection":1,"bucketKey":1}, {"unique":true});

db.ExternalForecastingScalarTimeSeries.createIndexes(
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"ensembleId":1,"ensembleMemberId":1,"forecastTime":1}, {"unique":true});

db.ExternalForecastingScalarTimeSeries.createIndexes(
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"forecastTime":1},
{"moduleInstanceId":1,"locationId":1,"forecastTime":1},
{"moduleInstanceId":1,"parameterId":1,"forecastTime":1},
{"locationId":1,"parameterId":1,"forecastTime":1},
{"moduleInstanceId":1,"forecastTime":1},
{"locationId":1,"forecastTime":1},
{"parameterId":1,"forecastTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"locationId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"parameterId":1,"metaData.modifiedTime":1},
{"locationId":1,"parameterId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"metaData.modifiedTime":1},
{"locationId":1,"metaData.modifiedTime":1},
{"parameterId":1,"metaData.modifiedTime":1},
{"metaData.modifiedTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1},
{"moduleInstanceId":1,"locationId":1},
{"moduleInstanceId":1,"parameterId":1},
{"locationId":1,"parameterId":1},
{"moduleInstanceId":1},
{"locationId":1},
{"parameterId":1},
{"forecastTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"locationId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"parameterId":1,"startTime":1,"endTime":1},
{"locationId":1,"parameterId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"startTime":1,"endTime":1},
{"locationId":1,"startTime":1,"endTime":1},
{"parameterId":1,"startTime":1,"endTime":1},
{"forecastTime":1,"startTime":1,"endTime":1},
{"startTime":1,"endTime":1},
{"encodedTimeStepId":1},
{"metaData.sourceId":1},
{"encodedTimeStepId":1,"forecastTime":1},
{"encodedTimeStepId":1,"metaData.areaId":1,"forecastTime":1,"metaData.sourceId":1},
{"parameterId":1,"metaData.areaId":1,"forecastTime":1,"metaData.sourceId":1},
{"moduleInstanceId":1,"metaData.areaId":1,"forecastTime":1,"metaData.sourceId":1},
{"metaData.areaId":1,"forecastTime":1,"moduleInstanceId":1,"parameterId":1,"encodedTimeStepId":1,"metaData.sourceId":1},
{"moduleInstanceId":1,"parameterId":1,"encodedTimeStepId":1,"metaData.areaId":1,"metaData.sourceId":1},
{"committed":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"localForecastTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"localForecastTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"forecastTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"forecastTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"localForecastTime":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"localForecastTime":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"forecastTime":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"forecastTime":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"ensembleId":1}, {});

db.ExternalHistoricalScalarTimeSeries.createIndexes(
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"bucketSize":1,"bucket":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"startTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"endTime":1}, {"unique":true});

db.ExternalHistoricalScalarTimeSeries.createIndexes(
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"locationId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"parameterId":1,"metaData.modifiedTime":1},
{"locationId":1,"parameterId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"metaData.modifiedTime":1},
{"locationId":1,"metaData.modifiedTime":1},
{"parameterId":1,"metaData.modifiedTime":1},
{"metaData.modifiedTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"locationId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"parameterId":1,"startTime":1,"endTime":1},
{"locationId":1,"parameterId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"startTime":1,"endTime":1},
{"locationId":1,"startTime":1,"endTime":1},
{"parameterId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1},
{"moduleInstanceId":1,"locationId":1},
{"moduleInstanceId":1,"parameterId":1},
{"locationId":1,"parameterId":1},
{"moduleInstanceId":1},
{"locationId":1},
{"parameterId":1},
{"startTime":1,"endTime":1},
{"encodedTimeStepId":1},
{"metaData.sourceId":1},
{"encodedTimeStepId":1,"startTime":1,"endTime":1},
{"encodedTimeStepId":1,"metaData.areaId":1,"startTime":1,"endTime":1,"metaData.sourceId":1},
{"parameterId":1,"metaData.areaId":1,"startTime":1,"endTime":1,"metaData.sourceId":1},
{"moduleInstanceId":1,"metaData.areaId":1,"startTime":1,"endTime":1,"metaData.sourceId":1},
{"metaData.areaId":1,"startTime":1,"endTime":1,"moduleInstanceId":1,"parameterId":1,"encodedTimeStepId":1,"metaData.sourceId":1},
{"moduleInstanceId":1,"parameterId":1,"encodedTimeStepId":1,"metaData.areaId":1,"metaData.sourceId":1},
{"committed":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"metaData.timeStepMinutes":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"localStartTime":1,"localEndTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"localStartTime":1,"localEndTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1}, {});

db.ExternalHistoricalScalarTimeSeriesBucket.createIndexes(
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"bucketSize":1,"bucket":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"startTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"endTime":1}, {"unique":true});

db.ExternalHistoricalScalarTimeSeriesBucket.createIndexes(
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"locationId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"parameterId":1,"metaData.modifiedTime":1},
{"locationId":1,"parameterId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"metaData.modifiedTime":1},
{"locationId":1,"metaData.modifiedTime":1},
{"parameterId":1,"metaData.modifiedTime":1},
{"metaData.modifiedTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"locationId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"parameterId":1,"startTime":1,"endTime":1},
{"locationId":1,"parameterId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"startTime":1,"endTime":1},
{"locationId":1,"startTime":1,"endTime":1},
{"parameterId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1},
{"moduleInstanceId":1,"locationId":1},
{"moduleInstanceId":1,"parameterId":1},
{"locationId":1,"parameterId":1},
{"moduleInstanceId":1},
{"locationId":1},
{"parameterId":1},
{"startTime":1,"endTime":1},
{"encodedTimeStepId":1},
{"metaData.sourceId":1},
{"encodedTimeStepId":1,"startTime":1,"endTime":1},
{"encodedTimeStepId":1,"metaData.areaId":1,"startTime":1,"endTime":1,"metaData.sourceId":1},
{"parameterId":1,"metaData.areaId":1,"startTime":1,"endTime":1,"metaData.sourceId":1},
{"moduleInstanceId":1,"metaData.areaId":1,"startTime":1,"endTime":1,"metaData.sourceId":1},
{"metaData.areaId":1,"startTime":1,"endTime":1,"moduleInstanceId":1,"parameterId":1,"encodedTimeStepId":1,"metaData.sourceId":1},
{"moduleInstanceId":1,"parameterId":1,"encodedTimeStepId":1,"metaData.areaId":1,"metaData.sourceId":1},
{"committed":1}, {});

db.MigrateLog.createIndexes(
{"date":1},
{"errorCategory":1}, {});

db.MigrateMetaData.createIndexes(
{"metaDataFileRelativePath":1}, {"unique":true});

db.MigrateMetaData.createIndexes(
{"netcdfFiles.timeSeriesIds":1},
{"committed":1}, {});

db.SimulatedForecastingScalarTimeSeries.createIndexes(
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"ensembleId":1,"ensembleMemberId":1,"forecastTime":1,"taskRunId":1}, {"unique":true});

db.SimulatedForecastingScalarTimeSeries.createIndexes(
{"qualifierId":1,"ensembleId":1,"parameterId":1,"locationId":1,"forecastTime":1,"encodedTimeStepId":1,"moduleInstanceId":1,"ensembleMemberId":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"forecastTime":1},
{"moduleInstanceId":1,"locationId":1,"forecastTime":1},
{"moduleInstanceId":1,"parameterId":1,"forecastTime":1},
{"locationId":1,"parameterId":1,"forecastTime":1},
{"moduleInstanceId":1,"forecastTime":1},
{"locationId":1,"forecastTime":1},
{"parameterId":1,"forecastTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"locationId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"parameterId":1,"metaData.modifiedTime":1},
{"locationId":1,"parameterId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"metaData.modifiedTime":1},
{"locationId":1,"metaData.modifiedTime":1},
{"parameterId":1,"metaData.modifiedTime":1},
{"metaData.modifiedTime":1},
{"taskRunId":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1},
{"moduleInstanceId":1,"locationId":1},
{"moduleInstanceId":1,"parameterId":1},
{"locationId":1,"parameterId":1},
{"moduleInstanceId":1},
{"locationId":1},
{"parameterId":1},
{"forecastTime":1},
{"taskRunId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"locationId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"parameterId":1,"startTime":1,"endTime":1},
{"locationId":1,"parameterId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"startTime":1,"endTime":1},
{"locationId":1,"startTime":1,"endTime":1},
{"parameterId":1,"startTime":1,"endTime":1},
{"startTime":1,"endTime":1},
{"encodedTimeStepId":1},
{"metaData.sourceId":1},
{"encodedTimeStepId":1,"forecastTime":1},
{"encodedTimeStepId":1,"metaData.areaId":1,"forecastTime":1,"metaData.sourceId":1},
{"parameterId":1,"metaData.areaId":1,"forecastTime":1,"metaData.sourceId":1},
{"moduleInstanceId":1,"metaData.areaId":1,"forecastTime":1,"metaData.sourceId":1},
{"metaData.areaId":1,"forecastTime":1,"moduleInstanceId":1,"parameterId":1,"encodedTimeStepId":1,"metaData.sourceId":1},
{"moduleInstanceId":1,"parameterId":1,"encodedTimeStepId":1,"metaData.areaId":1,"metaData.sourceId":1},
{"committed":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"localForecastTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"localForecastTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"forecastTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"forecastTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"localForecastTime":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"localForecastTime":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"forecastTime":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"forecastTime":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"ensembleId":1}, {});

db.SimulatedHistoricalScalarTimeSeries.createIndexes(
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"ensembleId":1,"ensembleMemberId":1,"forecastTime":1,"taskRunId":1}, {"unique":true});

db.SimulatedHistoricalScalarTimeSeries.createIndexes(
{"qualifierId":1,"ensembleId":1,"parameterId":1,"locationId":1,"forecastTime":1,"encodedTimeStepId":1,"moduleInstanceId":1,"ensembleMemberId":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"ensembleId":1,"ensembleMemberId":1,"metaData.timeStepMinutes":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"ensembleId":1,"ensembleMemberId":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"forecastTime":1},
{"moduleInstanceId":1,"locationId":1,"forecastTime":1},
{"moduleInstanceId":1,"parameterId":1,"forecastTime":1},
{"locationId":1,"parameterId":1,"forecastTime":1},
{"moduleInstanceId":1,"forecastTime":1},
{"locationId":1,"forecastTime":1},
{"parameterId":1,"forecastTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"locationId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"parameterId":1,"metaData.modifiedTime":1},
{"locationId":1,"parameterId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"metaData.modifiedTime":1},
{"locationId":1,"metaData.modifiedTime":1},
{"parameterId":1,"metaData.modifiedTime":1},
{"metaData.modifiedTime":1},
{"taskRunId":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1},
{"moduleInstanceId":1,"locationId":1},
{"moduleInstanceId":1,"parameterId":1},
{"locationId":1,"parameterId":1},
{"moduleInstanceId":1},
{"locationId":1},
{"parameterId":1},
{"forecastTime":1},
{"taskRunId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"locationId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"parameterId":1,"startTime":1,"endTime":1},
{"locationId":1,"parameterId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"startTime":1,"endTime":1},
{"locationId":1,"startTime":1,"endTime":1},
{"parameterId":1,"startTime":1,"endTime":1},
{"startTime":1,"endTime":1},
{"encodedTimeStepId":1},
{"metaData.sourceId":1},
{"encodedTimeStepId":1,"forecastTime":1},
{"encodedTimeStepId":1,"metaData.areaId":1,"forecastTime":1,"metaData.sourceId":1},
{"parameterId":1,"metaData.areaId":1,"forecastTime":1,"metaData.sourceId":1},
{"moduleInstanceId":1,"metaData.areaId":1,"forecastTime":1,"metaData.sourceId":1},
{"metaData.areaId":1,"forecastTime":1,"moduleInstanceId":1,"parameterId":1,"encodedTimeStepId":1,"metaData.sourceId":1},
{"moduleInstanceId":1,"parameterId":1,"encodedTimeStepId":1,"metaData.areaId":1,"metaData.sourceId":1},
{"committed":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"localForecastTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"localForecastTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"forecastTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"forecastTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"localForecastTime":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"localForecastTime":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"forecastTime":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"forecastTime":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"ensembleId":1}, {});

db.SimulatedHistoricalScalarTimeSeriesStitched.createIndexes(
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"ensembleId":1,"ensembleMemberId":1,"bucketSize":1,"bucket":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"ensembleId":1,"ensembleMemberId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"ensembleId":1,"ensembleMemberId":1,"startTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"ensembleId":1,"ensembleMemberId":1,"endTime":1}, {"unique":true});

db.SimulatedHistoricalScalarTimeSeriesStitched.createIndexes(
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"ensembleId":1,"ensembleMemberId":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"locationId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"parameterId":1,"metaData.modifiedTime":1},
{"locationId":1,"parameterId":1,"metaData.modifiedTime":1},
{"moduleInstanceId":1,"metaData.modifiedTime":1},
{"locationId":1,"metaData.modifiedTime":1},
{"parameterId":1,"metaData.modifiedTime":1},
{"metaData.modifiedTime":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1},
{"moduleInstanceId":1,"locationId":1},
{"moduleInstanceId":1,"parameterId":1},
{"locationId":1,"parameterId":1},
{"moduleInstanceId":1},
{"locationId":1},
{"parameterId":1},
{"moduleInstanceId":1,"locationId":1,"parameterId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"locationId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"parameterId":1,"startTime":1,"endTime":1},
{"locationId":1,"parameterId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"startTime":1,"endTime":1},
{"locationId":1,"startTime":1,"endTime":1},
{"parameterId":1,"startTime":1,"endTime":1},
{"startTime":1,"endTime":1},
{"encodedTimeStepId":1},
{"encodedTimeStepId":1,"startTime":1,"endTime":1},
{"encodedTimeStepId":1,"metaData.areaId":1,"startTime":1,"endTime":1,"metaData.sourceId":1},
{"parameterId":1,"metaData.areaId":1,"startTime":1,"endTime":1,"metaData.sourceId":1},
{"moduleInstanceId":1,"metaData.areaId":1,"startTime":1,"endTime":1,"metaData.sourceId":1},
{"metaData.areaId":1,"startTime":1,"endTime":1,"moduleInstanceId":1,"parameterId":1,"encodedTimeStepId":1,"metaData.sourceId":1},
{"moduleInstanceId":1,"parameterId":1,"encodedTimeStepId":1,"metaData.areaId":1,"metaData.sourceId":1},
{"committed":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"localStartTime":1,"localEndTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"localStartTime":1,"localEndTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"startTime":1,"endTime":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"localStartTime":1,"localEndTime":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"localStartTime":1,"localEndTime":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"startTime":1,"endTime":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"startTime":1,"endTime":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"locationId":1,"ensembleId":1},
{"moduleInstanceId":1,"parameterId":1,"qualifierId":1,"encodedTimeStepId":1,"ensembleId":1}, {});

db.TimeSeriesIndex.createIndexes(
{"collection":1,"moduleInstanceId":1,"parameterId":1,"encodedTimeStepId":1,"areaId":1,"sourceId":1}, {"unique":true});

db.TimeSeriesIndex.createIndexes(
{"collection":1,"moduleInstanceId":1},
{"collection":1,"parameterId":1},
{"collection":1,"encodedTimeStepId":1},
{"collection":1,"areaId":1},
{"collection":1,"sourceId":1},
{"collection":1,"moduleInstanceId":1,"areaId":1,"sourceId":1},
{"collection":1,"parameterId":1,"areaId":1,"sourceId":1},
{"collection":1,"encodedTimeStepId":1,"areaId":1,"sourceId":1}, {});

