name: env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - setuptools
  - wheel
  - pysolar
  - requests
  - xmltodict
  - netcdf4
  - cfgrib
  - zarr
  - cdsapi
  - eccodes
  - cartopy
  - chex
  - dask
  - dm-haiku
  - dm-tree
  - jraph
  - matplotlib
  - numpy
  - pandas
  - rtree
  - scipy
  - trimesh
  - typing_extensions
  - xarray
  - jax[cpu]
  - pip:
      - colabtools
      - xarray_tensorstore
      - dinosaur-dycore