db.getCollection('__sql_schemas').drop()
db.getCollection('__sql_schemas').insertMany([
    {
        "_id" : "view.ExternalForecastingScalarTimeSeriesHeader",
        "type" : "View",
        "lastUpdated" : new Date(),
        "schema" : {
            "bsonType" : "object",
            "properties" : {
                "ID" : { "bsonType" : "objectId" },
                "Committed" : { "bsonType" : "bool" },
                "EncodedTimeStepId" : { "bsonType" : "string" },
                "EndTime" : { "bsonType" : "date" },
                "EnsembleId" : { "bsonType" : "string" },
                "EnsembleMemberId" : { "bsonType" : "string" },
                "ForecastTime" : { "bsonType" : "date" },
                "LocalEndTime" : { "bsonType" : "date" },
                "LocalForecastTime" : { "bsonType" : "date" },
                "LocalStartTime" : { "bsonType" : "date" },
                "LocationId" : { "bsonType" : "string" },
                "MetaDataArchiveTime" : { "bsonType" : "date" },
                "MetaDataAreaId" : { "bsonType" : "string" },
                "MetaDataDisplayUnit" : { "bsonType" : "string" },
                "MetaDataEnsembleMemberIndex" : { "bsonType" : "int" },
                "MetaDataLocalTimeZone" : { "bsonType" : "string" },
                "MetaDataLocationName" : { "bsonType" : "string" },
                "MetaDataModifiedTime" : { "bsonType" : "date" },
                "MetaDataParameterName" : { "bsonType" : "string" },
                "MetaDataParameterType" : { "bsonType" : "string" },
                "MetaDataSourceId" : { "bsonType" : "string" },
                "MetaDataTimeStepLabel" : { "bsonType" : "string" },
                "MetaDataTimeStepMinutes" : { "bsonType" : "int" },
                "MetaDataUnit" : { "bsonType" : "string" },
                "ModuleInstanceId" : { "bsonType" : "string" },
                "ParameterId" : { "bsonType" : "string" },
                "QualifierId" : { "bsonType" : "string" },
                "StartTime" : { "bsonType" : "date" },
                "TimeSeriesType" : { "bsonType" : "string" }
            }
        }
    },
	{
        "_id" : "view.ExternalForecastingScalarTimeSeries",
        "type" : "View",
        "lastUpdated" : new Date(),
        "schema" : {
            "bsonType" : "object",
            "properties" : {
                "ID" : { "bsonType" : "objectId" },
                "Committed" : { "bsonType" : "bool" },
                "EncodedTimeStepId" : { "bsonType" : "string" },
                "EndTime" : { "bsonType" : "date" },
                "EnsembleId" : { "bsonType" : "string" },
                "EnsembleMemberId" : { "bsonType" : "string" },
                "ForecastTime" : { "bsonType" : "date" },
                "LocalEndTime" : { "bsonType" : "date" },
                "LocalForecastTime" : { "bsonType" : "date" },
                "LocalStartTime" : { "bsonType" : "date" },
                "LocationId" : { "bsonType" : "string" },
                "MetaDataArchiveTime" : { "bsonType" : "date" },
                "MetaDataAreaId" : { "bsonType" : "string" },
                "MetaDataDisplayUnit" : { "bsonType" : "string" },
                "MetaDataEnsembleMemberIndex" : { "bsonType" : "int" },
                "MetaDataLocalTimeZone" : { "bsonType" : "string" },
                "MetaDataLocationName" : { "bsonType" : "string" },
                "MetaDataModifiedTime" : { "bsonType" : "date" },
                "MetaDataParameterName" : { "bsonType" : "string" },
                "MetaDataParameterType" : { "bsonType" : "string" },
                "MetaDataSourceId" : { "bsonType" : "string" },
                "MetaDataTimeStepLabel" : { "bsonType" : "string" },
                "MetaDataTimeStepMinutes" : { "bsonType" : "int" },
                "MetaDataUnit" : { "bsonType" : "string" },
                "ModuleInstanceId" : { "bsonType" : "string" },
                "ParameterId" : { "bsonType" : "string" },
                "QualifierId" : { "bsonType" : "string" },
                "StartTime" : { "bsonType" : "date" },
                "TimeSeriesType" : { "bsonType" : "string" },
                "Comment" : { "bsonType" : "string" },
                "DisplayValue" : { "bsonType" : "double" },
                "Flag" : { "bsonType" : "int" },
                "LocalTime" : { "bsonType" : "date" },
                "Time" : { "bsonType" : "date" },
                "Value" : { "bsonType" : "double" }
            }
        }
    },
    {
        "_id" : "view.ExternalHistoricalScalarTimeSeriesHeader",
        "type" : "View",
        "lastUpdated" : new Date(),
        "schema" : {
            "bsonType" : "object",
            "properties" : {
                "ID" : { "bsonType" : "objectId" },
                "Bucket" : { "bsonType" : "long" },
                "BucketSize" : { "bsonType" : "string" },
                "Committed" : { "bsonType" : "bool" },
                "EncodedTimeStepId" : { "bsonType" : "string" },
                "EndTime" : { "bsonType" : "date" },
                "LocalEndTime" : { "bsonType" : "date" },
                "LocalStartTime" : { "bsonType" : "date" },
                "LocationId" : { "bsonType" : "string" },
                "MetaDataArchiveTime" : { "bsonType" : "date" },
                "MetaDataAreaId" : { "bsonType" : "string" },
                "MetaDataDisplayUnit" : { "bsonType" : "string" },
                "MetaDataLocalTimeZone" : { "bsonType" : "string" },
                "MetaDataLocationName" : { "bsonType" : "string" },
                "MetaDataModifiedTime" : { "bsonType" : "date" },
                "MetaDataParameterName" : { "bsonType" : "string" },
                "MetaDataParameterType" : { "bsonType" : "string" },
                "MetaDataSourceId" : { "bsonType" : "string" },
                "MetaDataTimeStepLabel" : { "bsonType" : "string" },
                "MetaDataTimeStepMinutes" : { "bsonType" : "int" },
                "MetaDataUnit" : { "bsonType" : "string" },
                "ModuleInstanceId" : { "bsonType" : "string" },
                "ParameterId" : { "bsonType" : "string" },
                "QualifierId" : { "bsonType" : "string" },
                "StartTime" : { "bsonType" : "date" },
                "TimeSeriesType" : { "bsonType" : "string" }
            }
        }
    },
	{
        "_id" : "view.ExternalHistoricalScalarTimeSeries",
        "type" : "View",
        "lastUpdated" : new Date(),
        "schema" : {
            "bsonType" : "object",
            "properties" : {
                "ID" : { "bsonType" : "objectId" },
                "Bucket" : { "bsonType" : "long" },
                "BucketSize" : { "bsonType" : "string" },
                "Committed" : { "bsonType" : "bool" },
                "EncodedTimeStepId" : { "bsonType" : "string" },
                "EndTime" : { "bsonType" : "date" },
                "LocalEndTime" : { "bsonType" : "date" },
                "LocalStartTime" : { "bsonType" : "date" },
                "LocationId" : { "bsonType" : "string" },
                "MetaDataArchiveTime" : { "bsonType" : "date" },
                "MetaDataAreaId" : { "bsonType" : "string" },
                "MetaDataDisplayUnit" : { "bsonType" : "string" },
                "MetaDataLocalTimeZone" : { "bsonType" : "string" },
                "MetaDataLocationName" : { "bsonType" : "string" },
                "MetaDataModifiedTime" : { "bsonType" : "date" },
                "MetaDataParameterName" : { "bsonType" : "string" },
                "MetaDataParameterType" : { "bsonType" : "string" },
                "MetaDataSourceId" : { "bsonType" : "string" },
                "MetaDataTimeStepLabel" : { "bsonType" : "string" },
                "MetaDataTimeStepMinutes" : { "bsonType" : "int" },
                "MetaDataUnit" : { "bsonType" : "string" },
                "ModuleInstanceId" : { "bsonType" : "string" },
                "ParameterId" : { "bsonType" : "string" },
                "QualifierId" : { "bsonType" : "string" },
                "StartTime" : { "bsonType" : "date" },
                "TimeSeriesType" : { "bsonType" : "string" },
                "Comment" : { "bsonType" : "string" },
                "DisplayValue" : { "bsonType" : "double" },
                "Flag" : { "bsonType" : "int" },
                "LocalTime" : { "bsonType" : "date" },
                "Time" : { "bsonType" : "date" },
                "Value" : { "bsonType" : "double" }
            }
        }
    },
    {
        "_id" : "view.SimulatedForecastingScalarTimeSeriesHeader",
        "type" : "View",
        "lastUpdated" : new Date(),
        "schema" : {
            "bsonType" : "object",
            "properties" : {
                "ID" : { "bsonType" : "objectId" },
                "Committed" : { "bsonType" : "bool" },
                "EncodedTimeStepId" : { "bsonType" : "string" },
                "EndTime" : { "bsonType" : "date" },
                "EnsembleId" : { "bsonType" : "string" },
                "EnsembleMemberId" : { "bsonType" : "string" },
                "ForecastTime" : { "bsonType" : "date" },
                "LocalEndTime" : { "bsonType" : "date" },
                "LocalForecastTime" : { "bsonType" : "date" },
                "LocalStartTime" : { "bsonType" : "date" },
                "LocationId" : { "bsonType" : "string" },
                "MetaDataApprovedTime" : { "bsonType" : "date" },
                "MetaDataArchiveTime" : { "bsonType" : "date" },
                "MetaDataAreaId" : { "bsonType" : "string" },
                "MetaDataDisplayUnit" : { "bsonType" : "string" },
                "MetaDataEnsembleMemberIndex" : { "bsonType" : "int" },
                "MetaDataLocalTimeZone" : { "bsonType" : "string" },
                "MetaDataLocationName" : { "bsonType" : "string" },
                "MetaDataModifiedTime" : { "bsonType" : "date" },
                "MetaDataParameterName" : { "bsonType" : "string" },
                "MetaDataParameterType" : { "bsonType" : "string" },
                "MetaDataSourceId" : { "bsonType" : "string" },
                "MetaDataTimeStepLabel" : { "bsonType" : "string" },
                "MetaDataTimeStepMinutes" : { "bsonType" : "int" },
                "MetaDataUnit" : { "bsonType" : "string" },
                "ModuleInstanceId" : { "bsonType" : "string" },
                "ParameterId" : { "bsonType" : "string" },
                "QualifierId" : { "bsonType" : "string" },
                "RunInfoConfigRevisionNumber" : { "bsonType" : "string" },
                "RunInfoDispatchTime" : { "bsonType" : "date" },
                "RunInfoMcId" : { "bsonType" : "string" },
                "RunInfoTaskRunId" : { "bsonType" : "string" },
                "RunInfoTime0" : { "bsonType" : "date" },
                "RunInfoUserId" : { "bsonType" : "string" },
                "RunInfo.workflowId" : { "bsonType" : "string" },
                "StartTime" : { "bsonType" : "date" },
                "TaskRunId" : { "bsonType" : "string" },
                "TimeSeriesType" : { "bsonType" : "string" }
            }
        }
    },
	{
        "_id" : "view.SimulatedForecastingScalarTimeSeries",
        "type" : "View",
        "lastUpdated" : new Date(),
        "schema" : {
            "bsonType" : "object",
            "properties" : {
                "ID" : { "bsonType" : "objectId" },
                "Committed" : { "bsonType" : "bool" },
                "EncodedTimeStepId" : { "bsonType" : "string" },
                "EndTime" : { "bsonType" : "date" },
                "EnsembleId" : { "bsonType" : "string" },
                "EnsembleMemberId" : { "bsonType" : "string" },
                "ForecastTime" : { "bsonType" : "date" },
                "LocalEndTime" : { "bsonType" : "date" },
                "LocalForecastTime" : { "bsonType" : "date" },
                "LocalStartTime" : { "bsonType" : "date" },
                "LocationId" : { "bsonType" : "string" },
                "MetaDataApprovedTime" : { "bsonType" : "date" },
                "MetaDataArchiveTime" : { "bsonType" : "date" },
                "MetaDataAreaId" : { "bsonType" : "string" },
                "MetaDataDisplayUnit" : { "bsonType" : "string" },
                "MetaDataEnsembleMemberIndex" : { "bsonType" : "int" },
                "MetaDataLocalTimeZone" : { "bsonType" : "string" },
                "MetaDataLocationName" : { "bsonType" : "string" },
                "MetaDataModifiedTime" : { "bsonType" : "date" },
                "MetaDataParameterName" : { "bsonType" : "string" },
                "MetaDataParameterType" : { "bsonType" : "string" },
                "MetaDataSourceId" : { "bsonType" : "string" },
                "MetaDataTimeStepLabel" : { "bsonType" : "string" },
                "MetaDataTimeStepMinutes" : { "bsonType" : "int" },
                "MetaDataUnit" : { "bsonType" : "string" },
                "ModuleInstanceId" : { "bsonType" : "string" },
                "ParameterId" : { "bsonType" : "string" },
                "QualifierId" : { "bsonType" : "string" },
                "RunInfoConfigRevisionNumber" : { "bsonType" : "string" },
                "RunInfoDispatchTime" : { "bsonType" : "date" },
                "RunInfoMcId" : { "bsonType" : "string" },
                "RunInfoTaskRunId" : { "bsonType" : "string" },
                "RunInfoTime0" : { "bsonType" : "date" },
                "RunInfoUserId" : { "bsonType" : "string" },
                "RunInfo.workflowId" : { "bsonType" : "string" },
                "StartTime" : { "bsonType" : "date" },
                "TaskRunId" : { "bsonType" : "string" },
                "TimeSeriesType" : { "bsonType" : "string" },
                "Comment" : { "bsonType" : "string" },
                "DisplayValue" : { "bsonType" : "double" },
                "Flag" : { "bsonType" : "int" },
                "LocalTime" : { "bsonType" : "date" },
                "Time" : { "bsonType" : "date" },
                "Value" : { "bsonType" : "double" }
            }
        }
    },
    {
        "_id" : "view.SimulatedHistoricalScalarTimeSeriesHeader",
        "type" : "View",
        "lastUpdated" : new Date(),
        "schema" : {
            "bsonType" : "object",
            "properties" : {
                "ID" : { "bsonType" : "objectId" },
                "Committed" : { "bsonType" : "bool" },
                "EncodedTimeStepId" : { "bsonType" : "string" },
                "EndTime" : { "bsonType" : "date" },
                "EnsembleId" : { "bsonType" : "string" },
                "EnsembleMemberId" : { "bsonType" : "string" },
                "ForecastTime" : { "bsonType" : "date" },
                "LocalEndTime" : { "bsonType" : "date" },
                "LocalForecastTime" : { "bsonType" : "date" },
                "LocalStartTime" : { "bsonType" : "date" },
                "LocationId" : { "bsonType" : "string" },
                "MetaDataApprovedTime" : { "bsonType" : "date" },
                "MetaDataArchiveTime" : { "bsonType" : "date" },
                "MetaDataAreaId" : { "bsonType" : "string" },
                "MetaDataDisplayUnit" : { "bsonType" : "string" },
                "MetaDataEnsembleMemberIndex" : { "bsonType" : "int" },
                "MetaDataLocalTimeZone" : { "bsonType" : "string" },
                "MetaDataLocationName" : { "bsonType" : "string" },
                "MetaDataModifiedTime" : { "bsonType" : "date" },
                "MetaDataParameterName" : { "bsonType" : "string" },
                "MetaDataParameterType" : { "bsonType" : "string" },
                "MetaDataSourceId" : { "bsonType" : "string" },
                "MetaDataTimeStepLabel" : { "bsonType" : "string" },
                "MetaDataTimeStepMinutes" : { "bsonType" : "int" },
                "MetaDataUnit" : { "bsonType" : "string" },
                "ModuleInstanceId" : { "bsonType" : "string" },
                "ParameterId" : { "bsonType" : "string" },
                "QualifierId" : { "bsonType" : "string" },
                "RunInfoConfigRevisionNumber" : { "bsonType" : "string" },
                "RunInfoDispatchTime" : { "bsonType" : "date" },
                "RunInfoMcId" : { "bsonType" : "string" },
                "RunInfoTaskRunId" : { "bsonType" : "string" },
                "RunInfoTime0" : { "bsonType" : "date" },
                "RunInfoUserId" : { "bsonType" : "string" },
                "RunInfo.workflowId" : { "bsonType" : "string" },
                "StartTime" : { "bsonType" : "date" },
                "TaskRunId" : { "bsonType" : "string" },
                "TimeSeriesType" : { "bsonType" : "string" }
            }
        }
    },
	{
        "_id" : "view.SimulatedHistoricalScalarTimeSeries",
        "type" : "View",
        "lastUpdated" : new Date(),
        "schema" : {
            "bsonType" : "object",
            "properties" : {
                "ID" : { "bsonType" : "objectId" },
                "Committed" : { "bsonType" : "bool" },
                "EncodedTimeStepId" : { "bsonType" : "string" },
                "EndTime" : { "bsonType" : "date" },
                "EnsembleId" : { "bsonType" : "string" },
                "EnsembleMemberId" : { "bsonType" : "string" },
                "ForecastTime" : { "bsonType" : "date" },
                "LocalEndTime" : { "bsonType" : "date" },
                "LocalForecastTime" : { "bsonType" : "date" },
                "LocalStartTime" : { "bsonType" : "date" },
                "LocationId" : { "bsonType" : "string" },
                "MetaDataApprovedTime" : { "bsonType" : "date" },
                "MetaDataArchiveTime" : { "bsonType" : "date" },
                "MetaDataAreaId" : { "bsonType" : "string" },
                "MetaDataDisplayUnit" : { "bsonType" : "string" },
                "MetaDataEnsembleMemberIndex" : { "bsonType" : "int" },
                "MetaDataLocalTimeZone" : { "bsonType" : "string" },
                "MetaDataLocationName" : { "bsonType" : "string" },
                "MetaDataModifiedTime" : { "bsonType" : "date" },
                "MetaDataParameterName" : { "bsonType" : "string" },
                "MetaDataParameterType" : { "bsonType" : "string" },
                "MetaDataSourceId" : { "bsonType" : "string" },
                "MetaDataTimeStepLabel" : { "bsonType" : "string" },
                "MetaDataTimeStepMinutes" : { "bsonType" : "int" },
                "MetaDataUnit" : { "bsonType" : "string" },
                "ModuleInstanceId" : { "bsonType" : "string" },
                "ParameterId" : { "bsonType" : "string" },
                "QualifierId" : { "bsonType" : "string" },
                "RunInfoConfigRevisionNumber" : { "bsonType" : "string" },
                "RunInfoDispatchTime" : { "bsonType" : "date" },
                "RunInfoMcId" : { "bsonType" : "string" },
                "RunInfoTaskRunId" : { "bsonType" : "string" },
                "RunInfoTime0" : { "bsonType" : "date" },
                "RunInfoUserId" : { "bsonType" : "string" },
                "RunInfo.workflowId" : { "bsonType" : "string" },
                "StartTime" : { "bsonType" : "date" },
                "TaskRunId" : { "bsonType" : "string" },
                "TimeSeriesType" : { "bsonType" : "string" },
                "Comment" : { "bsonType" : "string" },
                "DisplayValue" : { "bsonType" : "double" },
                "Flag" : { "bsonType" : "int" },
                "LocalTime" : { "bsonType" : "date" },
                "Time" : { "bsonType" : "date" },
                "Value" : { "bsonType" : "double" }
            }
        }
    },
    {
        "_id" : "view.SimulatedHistoricalScalarTimeSeriesStitchedHeader",
        "type" : "View",
        "lastUpdated" : new Date(),
        "schema" : {
            "bsonType" : "object",
            "properties" : {
                "ID" : { "bsonType" : "objectId" },
                "Bucket" : { "bsonType" : "long" },
                "BucketSize" : { "bsonType" : "string" },
                "Committed" : { "bsonType" : "bool" },
                "EncodedTimeStepId" : { "bsonType" : "string" },
                "EndTime" : { "bsonType" : "date" },
                "EnsembleId" : { "bsonType" : "string" },
                "EnsembleMemberId" : { "bsonType" : "string" },
                "LocationId" : { "bsonType" : "string" },
                "MetaDataApprovedTime" : { "bsonType" : "date" },
                "MetaDataArchiveTime" : { "bsonType" : "date" },
                "MetaDataAreaId" : { "bsonType" : "string" },
                "MetaDataDisplayUnit" : { "bsonType" : "string" },
                "MetaDataEnsembleMemberIndex" : { "bsonType" : "int" },
                "MetaDataLocalTimeZone" : { "bsonType" : "string" },
                "MetaDataLocationName" : { "bsonType" : "string" },
                "MetaDataModifiedTime" : { "bsonType" : "date" },
                "MetaDataParameterName" : { "bsonType" : "string" },
                "MetaDataParameterType" : { "bsonType" : "string" },
                "MetaDataSourceId" : { "bsonType" : "string" },
                "MetaDataTimeStepLabel" : { "bsonType" : "string" },
                "MetaDataTimeStepMinutes" : { "bsonType" : "int" },
                "MetaDataUnit" : { "bsonType" : "string" },
                "ModuleInstanceId" : { "bsonType" : "string" },
                "ParameterId" : { "bsonType" : "string" },
                "QualifierId" : { "bsonType" : "string" },
                "StartTime" : { "bsonType" : "date" },
                "TimeSeriesType" : { "bsonType" : "string" }
            }
        }
    },
	{
        "_id" : "view.SimulatedHistoricalScalarTimeSeriesStitched",
        "type" : "View",
        "lastUpdated" : new Date(),
        "schema" : {
            "bsonType" : "object",
            "properties" : {
                "ID" : { "bsonType" : "objectId" },
                "Bucket" : { "bsonType" : "long" },
                "BucketSize" : { "bsonType" : "string" },
                "Committed" : { "bsonType" : "bool" },
                "EncodedTimeStepId" : { "bsonType" : "string" },
                "EndTime" : { "bsonType" : "date" },
                "EnsembleId" : { "bsonType" : "string" },
                "EnsembleMemberId" : { "bsonType" : "string" },
                "LocationId" : { "bsonType" : "string" },
                "MetaDataApprovedTime" : { "bsonType" : "date" },
                "MetaDataArchiveTime" : { "bsonType" : "date" },
                "MetaDataAreaId" : { "bsonType" : "string" },
                "MetaDataDisplayUnit" : { "bsonType" : "string" },
                "MetaDataEnsembleMemberIndex" : { "bsonType" : "int" },
                "MetaDataLocalTimeZone" : { "bsonType" : "string" },
                "MetaDataLocationName" : { "bsonType" : "string" },
                "MetaDataModifiedTime" : { "bsonType" : "date" },
                "MetaDataParameterName" : { "bsonType" : "string" },
                "MetaDataParameterType" : { "bsonType" : "string" },
                "MetaDataSourceId" : { "bsonType" : "string" },
                "MetaDataTimeStepLabel" : { "bsonType" : "string" },
                "MetaDataTimeStepMinutes" : { "bsonType" : "int" },
                "MetaDataUnit" : { "bsonType" : "string" },
                "ModuleInstanceId" : { "bsonType" : "string" },
                "ParameterId" : { "bsonType" : "string" },
                "QualifierId" : { "bsonType" : "string" },
                "StartTime" : { "bsonType" : "date" },
                "TimeSeriesType" : { "bsonType" : "string" },
                "Comment" : { "bsonType" : "string" },
                "DisplayValue" : { "bsonType" : "double" },
                "Flag" : { "bsonType" : "int" },
                "LocalTime" : { "bsonType" : "date" },
                "Time" : { "bsonType" : "date" },
                "Value" : { "bsonType" : "double" }
            }
        }
    }
])