package nl.fews.archivedatabase.postgres.database;

import nl.fews.archivedatabase.common.shared.database.Table;
import nl.fews.archivedatabase.common.shared.enums.TimeSeriesType;
import nl.fews.archivedatabase.common.shared.utils.TimeSeriesTypeUtil;

import java.util.List;
import java.util.Map;
import java.util.Set;

public final class Schema {
	
	/**
	 * Static Class
	 */
	private Schema(){}

	/**
	 *
	 */
	private static final List<String> timeseriesFields = List.of("t", "lt", "v","dv", "f", "u", "c","fs");

	/**
	 *
	 */
	private static final Set<String> timeseriesValueFields = Set.of("v","dv");

	/**
	 *
	 * @return List<String>
	 */
	public static List<String> getTimeseriesFields(){
		return timeseriesFields;
	}

	/**
	 *
	 * @return Set<String>
	 */
	public static Set<String> getTimeseriesValueFields(){
		return timeseriesValueFields;
	}
	
	/**
	 *
	 * @param collection collection
	 * @return String
	 */
	public static String getSchema(String collection) {
		return Schema.schema.get(collection);
	}

	/**
	 *
	 * @return String
	 */
	public static Map<String, String> getSchemas() {
		return Schema.schema;
	}

	/**
	 *
	 * @return all collections / tables
	 */
	public static Set<String> getTables() {
		return Schema.schema.keySet();
	}
	
	/**
	 *
	 * @return String
	 */
	public static String getDatabase() {
		return database;
	}
	
	/**
	 *
	 * @return String
	 */
	public static String getSettings() {
		return settings;
	}
	
	private static final String database = "CREATE DATABASE IF NOT EXISTS \"FEWS_ARCHIVE\" WITH OWNER = postgres ENCODING = 'UTF8' LC_COLLATE = 'C' LC_CTYPE = 'C';";
	
	private static final String settings = "CREATE EXTENSION IF NOT EXISTS pg_stat_statements;";

	private static final Map<String, String> schema = Map.of(
		TimeSeriesTypeUtil.getTimeSeriesTypeCollection(TimeSeriesType.SCALAR_EXTERNAL_FORECASTING), """
CREATE TABLE IF NOT EXISTS "ExternalForecastingScalarTimeSeries" (
	"_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

	"timeSeriesType" TEXT NOT NULL,
	"moduleInstanceId" TEXT NOT NULL,
	"locationId" TEXT NOT NULL,
	"parameterId" TEXT NOT NULL,
	"qualifierIds" TEXT[] NOT NULL DEFAULT '{}',
	"qualifierId" TEXT NOT NULL DEFAULT '',
	"encodedTimeStepId" TEXT NOT NULL,
	"startTime" TIMESTAMP NOT NULL,
	"endTime" TIMESTAMP NOT NULL,
	"localStartTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"localEndTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"ensembleId" TEXT NOT NULL DEFAULT '',
	"ensembleMemberId" TEXT NOT NULL DEFAULT '',
	"forecastTime" TIMESTAMP NOT NULL,
	"localForecastTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"committed" BOOLEAN NOT NULL DEFAULT false,

	"metaData_sourceId" TEXT NOT NULL DEFAULT '',
	"metaData_areaId" TEXT NOT NULL DEFAULT '',
	"metaData_unit" TEXT NOT NULL DEFAULT '',
	"metaData_displayUnit" TEXT NOT NULL DEFAULT '',
	"metaData_LocationName" TEXT NOT NULL DEFAULT '',
	"metaData_parameterName" TEXT NOT NULL DEFAULT '',
	"metaData_parameterType" TEXT NOT NULL DEFAULT '',
	"metaData_timeStepLabel" TEXT NOT NULL DEFAULT '',
	"metaData_timeStepMinutes" INT NOT NULL DEFAULT 0,
	"metaData_localTimeZone" TEXT NOT NULL DEFAULT '',
	"metaData_archiveTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"metaData_modifiedTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"metaData_ensembleMemberIndex" INT NOT NULL DEFAULT 0,

	"timeseries_t" TIMESTAMP[] NOT NULL,
	"timeseries_lt" TIMESTAMP[] NOT NULL',
	"timeseries_v" REAL[] NOT NULL,
	"timeseries_dv" REAL[] NOT NULL,
	"timeseries_f" SMALLINT[] NOT NULL,
	"timeseries_u" TEXT[] NOT NULL,
	"timeseries_c" TEXT[] NOT NULL,
	"timeseries_fs" TEXT[] NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "efsts_mo_lo_pa_qu_et_en_em_ft_key" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "ensembleId", "ensembleMemberId", "forecastTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_lo_pa_ft_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "forecastTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_lo_ft_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "locationId", "forecastTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_ft_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "forecastTime");
CREATE INDEX IF NOT EXISTS "efsts_lo_pa_ft_idx" ON "ExternalForecastingScalarTimeSeries" ("locationId", "parameterId", "forecastTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_ft_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "forecastTime");
CREATE INDEX IF NOT EXISTS "efsts_lo_ft_idx" ON "ExternalForecastingScalarTimeSeries" ("locationId", "forecastTime");
CREATE INDEX IF NOT EXISTS "efsts_pa_ft_idx" ON "ExternalForecastingScalarTimeSeries" ("parameterId", "forecastTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_lo_pa_mt_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_lo_mt_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "locationId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_mt_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "efsts_lo_pa_mt_idx" ON "ExternalForecastingScalarTimeSeries" ("locationId", "parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_mt_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "efsts_lo_mt_idx" ON "ExternalForecastingScalarTimeSeries" ("locationId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "efsts_pa_mt_idx" ON "ExternalForecastingScalarTimeSeries" ("parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "efsts_mt_idx" ON "ExternalForecastingScalarTimeSeries" ("modifiedTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_qu_et_lo_lf_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "localForecastTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_qu_et_lf_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "localForecastTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_qu_et_lo_ft_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "forecastTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_qu_et_ft_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "forecastTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_qu_et_lo_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_qu_et_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_qu_et_lo_lf_en_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "localForecastTime", "ensembleId");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_qu_et_lf_en_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "localForecastTime", "ensembleId");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_qu_et_lo_ft_en_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "forecastTime", "ensembleId");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_qu_et_ft_en_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "forecastTime", "ensembleId");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_qu_et_lo_en_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "ensembleId");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_qu_et_en_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "ensembleId");
CREATE INDEX IF NOT EXISTS "efsts_mo_lo_pa_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId");
CREATE INDEX IF NOT EXISTS "efsts_mo_lo_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "locationId");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId");
CREATE INDEX IF NOT EXISTS "efsts_lo_pa_idx" ON "ExternalForecastingScalarTimeSeries" ("locationId", "parameterId");
CREATE INDEX IF NOT EXISTS "efsts_mo_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId");
CREATE INDEX IF NOT EXISTS "efsts_lo_idx" ON "ExternalForecastingScalarTimeSeries" ("locationId");
CREATE INDEX IF NOT EXISTS "efsts_pa_idx" ON "ExternalForecastingScalarTimeSeries" ("parameterId");
CREATE INDEX IF NOT EXISTS "efsts_ft_idx" ON "ExternalForecastingScalarTimeSeries" ("forecastTime");
CREATE INDEX IF NOT EXISTS "efsts_lf_idx" ON "ExternalForecastingScalarTimeSeries" ("localForecastTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_lo_pa_st_nt_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_lo_st_nt_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "locationId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_st_nt_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "efsts_lo_pa_st_nt_idx" ON "ExternalForecastingScalarTimeSeries" ("locationId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "efsts_mo_st_nt_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "efsts_lo_st_nt_idx" ON "ExternalForecastingScalarTimeSeries" ("locationId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "efsts_pa_st_nt_idx" ON "ExternalForecastingScalarTimeSeries" ("parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "efsts_ft_st_nt_idx" ON "ExternalForecastingScalarTimeSeries" ("forecastTime", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "efsts_st_nt_idx" ON "ExternalForecastingScalarTimeSeries" ("startTime", "endTime");
CREATE INDEX IF NOT EXISTS "efsts_et_idx" ON "ExternalForecastingScalarTimeSeries" ("encodedTimeStepId");
CREATE INDEX IF NOT EXISTS "efsts_ms_idx" ON "ExternalForecastingScalarTimeSeries" ("sourceId");
CREATE INDEX IF NOT EXISTS "efsts_et_ft_idx" ON "ExternalForecastingScalarTimeSeries" ("encodedTimeStepId", "forecastTime");
CREATE INDEX IF NOT EXISTS "efsts_et_ma_ft_ms_idx" ON "ExternalForecastingScalarTimeSeries" ("encodedTimeStepId", "areaId", "forecastTime", "sourceId");
CREATE INDEX IF NOT EXISTS "efsts_pa_ma_ft_ms_idx" ON "ExternalForecastingScalarTimeSeries" ("parameterId", "areaId", "forecastTime", "sourceId");
CREATE INDEX IF NOT EXISTS "efsts_mo_ma_ft_ms_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "areaId", "forecastTime", "sourceId");
CREATE INDEX IF NOT EXISTS "efsts_ma_ft_mo_pa_et_ms_idx" ON "ExternalForecastingScalarTimeSeries" ("areaId", "forecastTime", "moduleInstanceId", "parameterId", "encodedTimeStepId", "sourceId");
CREATE INDEX IF NOT EXISTS "efsts_mo_pa_et_ma_ms_idx" ON "ExternalForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "encodedTimeStepId", "areaId", "sourceId");
CREATE INDEX IF NOT EXISTS "efsts_co_idx" ON "ExternalForecastingScalarTimeSeries" ("committed");""",
		TimeSeriesTypeUtil.getTimeSeriesTypeCollection(TimeSeriesType.SCALAR_EXTERNAL_HISTORICAL), """
CREATE TABLE IF NOT EXISTS "ExternalHistoricalScalarTimeSeries" (
	"_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

	"timeSeriesType" TEXT NOT NULL,
	"moduleInstanceId" TEXT NOT NULL,
	"locationId" TEXT NOT NULL,
	"parameterId" TEXT NOT NULL,
	"qualifierIds" TEXT[] NOT NULL DEFAULT '{}',
	"qualifierId" TEXT NOT NULL DEFAULT '',
	"encodedTimeStepId" TEXT NOT NULL,
	"startTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"endTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"localStartTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"localEndTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"committed" BOOLEAN NOT NULL DEFAULT false,
	"bucketSize" TEXT NOT NULL DEFAULT '',
	"bucket" BIGINT NOT NULL DEFAULT 0,

	"metaData_sourceId" TEXT NOT NULL DEFAULT '',
	"metaData_areaId" TEXT NOT NULL DEFAULT '',
	"metaData_unit" TEXT NOT NULL DEFAULT '',
	"metaData_displayUnit" TEXT NOT NULL DEFAULT '',
	"metaData_locationName" TEXT NOT NULL DEFAULT '',
	"metaData_parameterName" TEXT NOT NULL DEFAULT '',
	"metaData_parameterType" TEXT NOT NULL DEFAULT '',
	"metaData_timeStepLabel" TEXT NOT NULL DEFAULT '',
	"metaData_timeStepMinutes" INT NOT NULL DEFAULT 0,
	"metaData_localTimeZone" TEXT NOT NULL DEFAULT '',
	"metaData_archiveTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"metaData_modifiedTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	
	"timeseries_t" TIMESTAMP[] NOT NULL,
	"timeseries_lt" TIMESTAMP[] NOT NULL',
	"timeseries_v" REAL[] NOT NULL,
	"timeseries_dv" REAL[] NOT NULL,
	"timeseries_f" SMALLINT[] NOT NULL,
	"timeseries_u" TEXT[] NOT NULL,
	"timeseries_c" TEXT[] NOT NULL,
	"timeseries_fs" TEXT[] NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "ehsts_mo_lo_pa_qu_et_bu_bk_key" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "bucketSize", "bucket");
CREATE UNIQUE INDEX IF NOT EXISTS "ehsts_mo_lo_pa_qu_et_st_nt_key" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "startTime", "endTime");
CREATE UNIQUE INDEX IF NOT EXISTS "ehsts_mo_lo_pa_qu_et_st_key" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "startTime");
CREATE UNIQUE INDEX IF NOT EXISTS "ehsts_mo_lo_pa_qu_et_nt_key" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "endTime");
CREATE INDEX IF NOT EXISTS "ehsts_mo_lo_pa_qu_et_tm_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "timeStepMinutes");
CREATE INDEX IF NOT EXISTS "ehsts_mo_lo_pa_qu_et_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId");
CREATE INDEX IF NOT EXISTS "ehsts_mo_lo_pa_mt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "ehsts_mo_lo_mt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "ehsts_mo_pa_mt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "ehsts_lo_pa_mt_idx" ON "ExternalHistoricalScalarTimeSeries" ("locationId", "parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "ehsts_mo_mt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "ehsts_lo_mt_idx" ON "ExternalHistoricalScalarTimeSeries" ("locationId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "ehsts_pa_mt_idx" ON "ExternalHistoricalScalarTimeSeries" ("parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "ehsts_mt_idx" ON "ExternalHistoricalScalarTimeSeries" ("modifiedTime");
CREATE INDEX IF NOT EXISTS "ehsts_mo_lo_pa_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehsts_mo_lo_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehsts_mo_pa_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehsts_lo_pa_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("locationId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehsts_mo_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehsts_lo_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("locationId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehsts_pa_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehsts_mo_pa_qu_et_lo_lst_lnt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "localStartTime", "localEndTime");
CREATE INDEX IF NOT EXISTS "ehsts_mo_pa_qu_et_lst_lnt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "localStartTime", "localEndTime");
CREATE INDEX IF NOT EXISTS "ehsts_mo_pa_qu_et_lo_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehsts_mo_pa_qu_et_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehsts_mo_pa_qu_et_lo_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId");
CREATE INDEX IF NOT EXISTS "ehsts_mo_pa_qu_et_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId");
CREATE INDEX IF NOT EXISTS "ehsts_mo_lo_pa_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId");
CREATE INDEX IF NOT EXISTS "ehsts_mo_lo_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId");
CREATE INDEX IF NOT EXISTS "ehsts_mo_pa_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId");
CREATE INDEX IF NOT EXISTS "ehsts_lo_pa_idx" ON "ExternalHistoricalScalarTimeSeries" ("locationId", "parameterId");
CREATE INDEX IF NOT EXISTS "ehsts_mo_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId");
CREATE INDEX IF NOT EXISTS "ehsts_lo_idx" ON "ExternalHistoricalScalarTimeSeries" ("locationId");
CREATE INDEX IF NOT EXISTS "ehsts_pa_idx" ON "ExternalHistoricalScalarTimeSeries" ("parameterId");
CREATE INDEX IF NOT EXISTS "ehsts_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehsts_lst_lnt_idx" ON "ExternalHistoricalScalarTimeSeries" ("localStartTime", "localEndTime");
CREATE INDEX IF NOT EXISTS "ehsts_et_idx" ON "ExternalHistoricalScalarTimeSeries" ("encodedTimeStepId");
CREATE INDEX IF NOT EXISTS "ehsts_ms_idx" ON "ExternalHistoricalScalarTimeSeries" ("sourceId");
CREATE INDEX IF NOT EXISTS "ehsts_et_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("encodedTimeStepId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehsts_et_ma_st_nt_ms_idx" ON "ExternalHistoricalScalarTimeSeries" ("encodedTimeStepId", "areaId", "startTime", "endTime", "sourceId");
CREATE INDEX IF NOT EXISTS "ehsts_pa_ma_st_nt_ms_idx" ON "ExternalHistoricalScalarTimeSeries" ("parameterId", "areaId", "startTime", "endTime", "sourceId");
CREATE INDEX IF NOT EXISTS "ehsts_mo_ma_st_nt_ms_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "areaId", "startTime", "endTime", "sourceId");
CREATE INDEX IF NOT EXISTS "ehsts_ma_st_nt_mo_pa_et_ms_idx" ON "ExternalHistoricalScalarTimeSeries" ("areaId", "startTime", "endTime", "moduleInstanceId", "parameterId", "encodedTimeStepId", "sourceId");
CREATE INDEX IF NOT EXISTS "ehsts_mo_pa_et_ma_ms_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "encodedTimeStepId", "areaId", "sourceId");
CREATE INDEX IF NOT EXISTS "ehsts_co_idx" ON "ExternalHistoricalScalarTimeSeries" ("committed");""",
		TimeSeriesTypeUtil.getTimeSeriesTypeCollection(TimeSeriesType.SCALAR_EXTERNAL_HISTORICAL_BUCKET),"""
CREATE TABLE IF NOT EXISTS "ExternalHistoricalScalarTimeSeriesBucket" (
	"_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

	"timeSeriesType" TEXT NOT NULL,
	"moduleInstanceId" TEXT NOT NULL,
	"locationId" TEXT NOT NULL,
	"parameterId" TEXT NOT NULL,
	"qualifierIds" TEXT[] NOT NULL DEFAULT '{}',
	"qualifierId" TEXT NOT NULL DEFAULT '',
	"encodedTimeStepId" TEXT NOT NULL,
	"startTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"endTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"localStartTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"localEndTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"committed" BOOLEAN NOT NULL DEFAULT false,
	"bucketSize" TEXT NOT NULL DEFAULT '',
	"bucket" BIGINT NOT NULL DEFAULT 0,

	"metaData_sourceId" TEXT NOT NULL DEFAULT '',
	"metaData_areaId" TEXT NOT NULL DEFAULT '',
	"metaData_unit" TEXT NOT NULL DEFAULT '',
	"metaData_displayUnit" TEXT NOT NULL DEFAULT '',
	"metaData_locationName" TEXT NOT NULL DEFAULT '',
	"metaData_parameterName" TEXT NOT NULL DEFAULT '',
	"metaData_parameterType" TEXT NOT NULL DEFAULT '',
	"metaData_timeStepLabel" TEXT NOT NULL DEFAULT '',
	"metaData_timeStepMinutes" INT NOT NULL DEFAULT 0,
	"metaData_localTimeZone" TEXT NOT NULL DEFAULT '',
	"metaData_archiveTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"metaData_modifiedTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	
	"timeseries_t" TIMESTAMP[] NOT NULL,
	"timeseries_lt" TIMESTAMP[] NOT NULL',
	"timeseries_v" REAL[] NOT NULL,
	"timeseries_dv" REAL[] NOT NULL,
	"timeseries_f" SMALLINT[] NOT NULL,
	"timeseries_u" TEXT[] NOT NULL,
	"timeseries_c" TEXT[] NOT NULL,
	"timeseries_fs" TEXT[] NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "ehstsb_mo_lo_pa_qu_et_bu_bk_key" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "bucketSize", "bucket");
CREATE UNIQUE INDEX IF NOT EXISTS "ehstsb_mo_lo_pa_qu_et_st_nt_key" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "startTime", "endTime");
CREATE UNIQUE INDEX IF NOT EXISTS "ehstsb_mo_lo_pa_qu_et_st_key" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "startTime");
CREATE UNIQUE INDEX IF NOT EXISTS "ehstsb_mo_lo_pa_qu_et_nt_key" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "endTime");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_lo_pa_qu_et_tm_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "timeStepMinutes");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_lo_pa_qu_et_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_lo_pa_mt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_lo_mt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_pa_mt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "ehstsb_lo_pa_mt_idx" ON "ExternalHistoricalScalarTimeSeries" ("locationId", "parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_mt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "ehstsb_lo_mt_idx" ON "ExternalHistoricalScalarTimeSeries" ("locationId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "ehstsb_pa_mt_idx" ON "ExternalHistoricalScalarTimeSeries" ("parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "ehstsb_mt_idx" ON "ExternalHistoricalScalarTimeSeries" ("modifiedTime");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_lo_pa_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_lo_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_pa_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehstsb_lo_pa_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("locationId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehstsb_lo_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("locationId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehstsb_pa_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_pa_qu_et_lo_lst_lnt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "localStartTime", "localEndTime");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_pa_qu_et_lst_lnt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "localStartTime", "localEndTime");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_pa_qu_et_lo_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_pa_qu_et_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_pa_qu_et_lo_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_pa_qu_et_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_lo_pa_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_lo_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_pa_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId");
CREATE INDEX IF NOT EXISTS "ehstsb_lo_pa_idx" ON "ExternalHistoricalScalarTimeSeries" ("locationId", "parameterId");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId");
CREATE INDEX IF NOT EXISTS "ehstsb_lo_idx" ON "ExternalHistoricalScalarTimeSeries" ("locationId");
CREATE INDEX IF NOT EXISTS "ehstsb_pa_idx" ON "ExternalHistoricalScalarTimeSeries" ("parameterId");
CREATE INDEX IF NOT EXISTS "ehstsb_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehstsb_lst_lnt_idx" ON "ExternalHistoricalScalarTimeSeries" ("localStartTime", "localEndTime");
CREATE INDEX IF NOT EXISTS "ehstsb_et_idx" ON "ExternalHistoricalScalarTimeSeries" ("encodedTimeStepId");
CREATE INDEX IF NOT EXISTS "ehstsb_ms_idx" ON "ExternalHistoricalScalarTimeSeries" ("sourceId");
CREATE INDEX IF NOT EXISTS "ehstsb_et_st_nt_idx" ON "ExternalHistoricalScalarTimeSeries" ("encodedTimeStepId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "ehstsb_et_ma_st_nt_ms_idx" ON "ExternalHistoricalScalarTimeSeries" ("encodedTimeStepId", "areaId", "startTime", "endTime", "sourceId");
CREATE INDEX IF NOT EXISTS "ehstsb_pa_ma_st_nt_ms_idx" ON "ExternalHistoricalScalarTimeSeries" ("parameterId", "areaId", "startTime", "endTime", "sourceId");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_ma_st_nt_ms_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "areaId", "startTime", "endTime", "sourceId");
CREATE INDEX IF NOT EXISTS "ehstsb_ma_st_nt_mo_pa_et_ms_idx" ON "ExternalHistoricalScalarTimeSeries" ("areaId", "startTime", "endTime", "moduleInstanceId", "parameterId", "encodedTimeStepId", "sourceId");
CREATE INDEX IF NOT EXISTS "ehstsb_mo_pa_et_ma_ms_idx" ON "ExternalHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "encodedTimeStepId", "areaId", "sourceId");
CREATE INDEX IF NOT EXISTS "ehstsb_co_idx" ON "ExternalHistoricalScalarTimeSeries" ("committed");""",
		TimeSeriesTypeUtil.getTimeSeriesTypeCollection(TimeSeriesType.SCALAR_SIMULATED_FORECASTING), """
CREATE TABLE IF NOT EXISTS "SimulatedForecastingScalarTimeSeries" (
	"_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	
	"timeSeriesType" TEXT NOT NULL,
	"moduleInstanceId" TEXT NOT NULL,
	"locationId" TEXT NOT NULL,
	"parameterId" TEXT NOT NULL,
	"qualifierIds" TEXT[] NOT NULL DEFAULT '{}',
	"qualifierId" TEXT NOT NULL DEFAULT '',
	"encodedTimeStepId" TEXT NOT NULL,
	"startTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"endTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"localStartTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"localEndTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"ensembleId" TEXT NOT NULL DEFAULT '',
	"ensembleMemberId" TEXT NOT NULL DEFAULT '',
	"forecastTime" TIMESTAMP NOT NULL,
	"localForecastTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"taskRunId" TEXT NOT NULL,
	"committed" BOOLEAN NOT NULL DEFAULT false,
	
	"metaData_sourceId" TEXT NOT NULL DEFAULT '',
	"metaData_areaId" TEXT NOT NULL DEFAULT '',
	"metaData_unit" TEXT NOT NULL DEFAULT '',
	"metaData_displayUnit" TEXT NOT NULL DEFAULT '',
	"metaData_locationName" TEXT NOT NULL DEFAULT '',
	"metaData_parameterName" TEXT NOT NULL DEFAULT '',
	"metaData_parameterType" TEXT NOT NULL DEFAULT '',
	"metaData_timeStepLabel" TEXT NOT NULL DEFAULT '',
	"metaData_timeStepMinutes" INT NOT NULL DEFAULT 0,
	"metaData_localTimeZone" TEXT NOT NULL DEFAULT '',
	"metaData_archiveTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"metaData_modifiedTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"metaData_ensembleMemberIndex" INT NOT NULL DEFAULT 0,
	"metaData_approvedTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	
	"runInfo_dispatchTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"runInfo_taskRunId" TEXT NOT NULL DEFAULT '',
	"runInfo_mcId" TEXT NOT NULL DEFAULT '',
	"runInfo_userId" TEXT NOT NULL DEFAULT '',
	"runInfo_time0" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"runInfo_workflowId" TEXT NOT NULL DEFAULT '',
	"runInfo_configRevisionNumber" TEXT NOT NULL DEFAULT '',
	
	"timeseries_t" TIMESTAMP[] NOT NULL,
	"timeseries_lt" TIMESTAMP[] NOT NULL',
	"timeseries_v" REAL[] NOT NULL,
	"timeseries_dv" REAL[] NOT NULL,
	"timeseries_f" SMALLINT[] NOT NULL,
	"timeseries_u" TEXT[] NOT NULL,
	"timeseries_c" TEXT[] NOT NULL,
	"timeseries_fs" TEXT[] NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "sfsts_mo_lo_pa_qu_et_en_em_ft_tr_key" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "ensembleId", "ensembleMemberId", "forecastTime", "taskRunId");
CREATE INDEX IF NOT EXISTS "sfsts_mo_lo_pa_ft_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "forecastTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_lo_ft_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "locationId", "forecastTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_pa_ft_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "forecastTime");
CREATE INDEX IF NOT EXISTS "sfsts_lo_pa_ft_idx" ON "SimulatedForecastingScalarTimeSeries" ("locationId", "parameterId", "forecastTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_ft_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "forecastTime");
CREATE INDEX IF NOT EXISTS "sfsts_lo_ft_idx" ON "SimulatedForecastingScalarTimeSeries" ("locationId", "forecastTime");
CREATE INDEX IF NOT EXISTS "sfsts_pa_ft_idx" ON "SimulatedForecastingScalarTimeSeries" ("parameterId", "forecastTime");
CREATE INDEX IF NOT EXISTS "sfsts_ft_idx" ON "SimulatedForecastingScalarTimeSeries" ("forecastTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_lo_pa_mt_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "metaDataModifiedTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_lo_mt_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "locationId", "metaDataModifiedTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_pa_mt_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "metaDataModifiedTime");
CREATE INDEX IF NOT EXISTS "sfsts_lo_pa_mt_idx" ON "SimulatedForecastingScalarTimeSeries" ("locationId", "parameterId", "metaDataModifiedTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_mt_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "metaDataModifiedTime");
CREATE INDEX IF NOT EXISTS "sfsts_lo_mt_idx" ON "SimulatedForecastingScalarTimeSeries" ("locationId", "metaDataModifiedTime");
CREATE INDEX IF NOT EXISTS "sfsts_pa_mt_idx" ON "SimulatedForecastingScalarTimeSeries" ("parameterId", "metaDataModifiedTime");
CREATE INDEX IF NOT EXISTS "sfsts_mt_idx" ON "SimulatedForecastingScalarTimeSeries" ("metaDataModifiedTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_lo_pa_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId");
CREATE INDEX IF NOT EXISTS "sfsts_mo_lo_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "locationId");
CREATE INDEX IF NOT EXISTS "sfsts_mo_pa_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId");
CREATE INDEX IF NOT EXISTS "sfsts_lo_pa_idx" ON "SimulatedForecastingScalarTimeSeries" ("locationId", "parameterId");
CREATE INDEX IF NOT EXISTS "sfsts_mo_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId");
CREATE INDEX IF NOT EXISTS "sfsts_lo_idx" ON "SimulatedForecastingScalarTimeSeries" ("locationId");
CREATE INDEX IF NOT EXISTS "sfsts_pa_idx" ON "SimulatedForecastingScalarTimeSeries" ("parameterId");
CREATE INDEX IF NOT EXISTS "sfsts_tr_st_nt_idx" ON "SimulatedForecastingScalarTimeSeries" ("taskRunId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_lo_pa_st_nt_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_lo_st_nt_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "locationId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_pa_st_nt_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "sfsts_lo_pa_st_nt_idx" ON "SimulatedForecastingScalarTimeSeries" ("locationId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_st_nt_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "sfsts_lo_st_nt_idx" ON "SimulatedForecastingScalarTimeSeries" ("locationId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "sfsts_pa_st_nt_idx" ON "SimulatedForecastingScalarTimeSeries" ("parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "sfsts_ft_st_nt_idx" ON "SimulatedForecastingScalarTimeSeries" ("forecastTime", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "sfsts_st_nt_idx" ON "SimulatedForecastingScalarTimeSeries" ("startTime", "endTime");
CREATE INDEX IF NOT EXISTS "sfsts_lf_idx" ON "SimulatedForecastingScalarTimeSeries" ("localForecastTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_pa_qu_et_lo_lf_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "localForecastTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_pa_qu_et_lf_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "localForecastTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_pa_qu_et_lo_ft_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "forecastTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_pa_qu_et_ft_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "forecastTime");
CREATE INDEX IF NOT EXISTS "sfsts_mo_pa_qu_et_lo_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId");
CREATE INDEX IF NOT EXISTS "sfsts_mo_pa_qu_et_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId");
CREATE INDEX IF NOT EXISTS "sfsts_mo_pa_qu_et_lo_lf_en_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "localForecastTime", "ensembleId");
CREATE INDEX IF NOT EXISTS "sfsts_mo_pa_qu_et_lf_en_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "localForecastTime", "ensembleId");
CREATE INDEX IF NOT EXISTS "sfsts_mo_pa_qu_et_lo_ft_en_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "forecastTime", "ensembleId");
CREATE INDEX IF NOT EXISTS "sfsts_mo_pa_qu_et_ft_en_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "forecastTime", "ensembleId");
CREATE INDEX IF NOT EXISTS "sfsts_mo_pa_qu_et_lo_en_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "ensembleId");
CREATE INDEX IF NOT EXISTS "sfsts_mo_pa_qu_et_en_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "ensembleId");
CREATE INDEX IF NOT EXISTS "sfsts_et_idx" ON "SimulatedForecastingScalarTimeSeries" ("encodedTimeStepId");
CREATE INDEX IF NOT EXISTS "sfsts_ms_idx" ON "SimulatedForecastingScalarTimeSeries" ("metaDataSourceId");
CREATE INDEX IF NOT EXISTS "sfsts_tr_idx" ON "SimulatedForecastingScalarTimeSeries" ("taskRunId");
CREATE INDEX IF NOT EXISTS "sfsts_co_idx" ON "SimulatedForecastingScalarTimeSeries" ("committed");
CREATE INDEX IF NOT EXISTS "sfsts_et_ft_idx" ON "SimulatedForecastingScalarTimeSeries" ("encodedTimeStepId", "forecastTime");
CREATE INDEX IF NOT EXISTS "sfsts_et_ma_ft_ms_idx" ON "SimulatedForecastingScalarTimeSeries" ("encodedTimeStepId", "metaDataAreaId", "forecastTime", "metaDataSourceId");
CREATE INDEX IF NOT EXISTS "sfsts_pa_ma_ft_ms_idx" ON "SimulatedForecastingScalarTimeSeries" ("parameterId", "metaDataAreaId", "forecastTime", "metaDataSourceId");
CREATE INDEX IF NOT EXISTS "sfsts_mo_ma_ft_ms_idx" ON "SimulatedForecastingScalarTimeSeries" ("moduleInstanceId", "metaDataAreaId", "forecastTime", "metaDataSourceId");
CREATE INDEX IF NOT EXISTS "sfsts_ma_ft_mo_pa_et_ms_idx" ON "SimulatedForecastingScalarTimeSeries" ("metaDataAreaId", "forecastTime", "moduleInstanceId", "parameterId", "encodedTimeStepId", "metaDataSourceId");""",
		TimeSeriesTypeUtil.getTimeSeriesTypeCollection(TimeSeriesType.SCALAR_SIMULATED_HISTORICAL), """
CREATE TABLE IF NOT EXISTS "SimulatedHistoricalScalarTimeSeries" (
	"_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

	"timeSeriesType" TEXT NOT NULL,
	"moduleInstanceId" TEXT NOT NULL,
	"locationId" TEXT NOT NULL,
	"parameterId" TEXT NOT NULL,
	"qualifierIds" TEXT[] NOT NULL DEFAULT '{}',
	"qualifierId" TEXT NOT NULL DEFAULT '',
	"encodedTimeStepId" TEXT NOT NULL,
	"startTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"endTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"localStartTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"localEndTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"ensembleId" TEXT NOT NULL DEFAULT '',
	"ensembleMemberId" TEXT NOT NULL DEFAULT '',
	"forecastTime" TIMESTAMP NOT NULL,
	"localForecastTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"taskRunId" TEXT NOT NULL,
	"committed" BOOLEAN NOT NULL DEFAULT false,

	"metaData_sourceId" TEXT NOT NULL DEFAULT '',
	"metaData_areaId" TEXT NOT NULL DEFAULT '',
	"metaData_unit" TEXT NOT NULL DEFAULT '',
	"metaData_displayUnit" TEXT NOT NULL DEFAULT '',
	"metaData_locationName" TEXT NOT NULL DEFAULT '',
	"metaData_parameterName" TEXT NOT NULL DEFAULT '',
	"metaData_parameterType" TEXT NOT NULL DEFAULT '',
	"metaData_timeStepLabel" TEXT NOT NULL DEFAULT '',
	"metaData_timeStepMinutes" INT NOT NULL DEFAULT 0,
	"metaData_localTimeZone" TEXT NOT NULL DEFAULT '',
	"metaData_archiveTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"metaData_modifiedTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"metaData_ensembleMemberIndex" INT NOT NULL DEFAULT 0,
	"metaData_approvedTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',

	"runInfo_dispatchTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"runInfo_taskRunId" TEXT NOT NULL DEFAULT '',
	"runInfo_mcId" TEXT NOT NULL DEFAULT '',
	"runInfo_userId" TEXT NOT NULL DEFAULT '',
	"runInfo_time0" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"runInfo_workflowId" TEXT NOT NULL DEFAULT '',
	"runInfo_configRevisionNumber" TEXT NOT NULL DEFAULT '',

	"timeseries_t" TIMESTAMP[] NOT NULL,
	"timeseries_lt" TIMESTAMP[] NOT NULL',
	"timeseries_v" REAL[] NOT NULL,
	"timeseries_dv" REAL[] NOT NULL,
	"timeseries_f" SMALLINT[] NOT NULL,
	"timeseries_u" TEXT[] NOT NULL,
	"timeseries_c" TEXT[] NOT NULL,
	"timeseries_fs" TEXT[] NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "shsts_mo_lo_pa_qu_et_en_em_ft_tr_key" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "ensembleId", "ensembleMemberId", "forecastTime", "taskRunId");
CREATE UNIQUE INDEX IF NOT EXISTS "shsts_mo_lo_pa_qu_et_en_em_ft_key" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "ensembleId", "ensembleMemberId", "forecastTime");
CREATE UNIQUE INDEX IF NOT EXISTS "shsts_mo_lo_pa_qu_et_en_em_tm_key" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "ensembleId", "ensembleMemberId", "timeStepMinutes");
CREATE UNIQUE INDEX IF NOT EXISTS "shsts_mo_lo_pa_qu_et_en_em_key" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "ensembleId", "ensembleMemberId");
CREATE INDEX IF NOT EXISTS "shsts_mo_lo_pa_ft_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "forecastTime");
CREATE INDEX IF NOT EXISTS "shsts_mo_lo_ft_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "forecastTime");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_ft_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "forecastTime");
CREATE INDEX IF NOT EXISTS "shsts_lo_pa_ft_idx" ON "SimulatedHistoricalScalarTimeSeries" ("locationId", "parameterId", "forecastTime");
CREATE INDEX IF NOT EXISTS "shsts_mo_ft_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "forecastTime");
CREATE INDEX IF NOT EXISTS "shsts_lo_ft_idx" ON "SimulatedHistoricalScalarTimeSeries" ("locationId", "forecastTime");
CREATE INDEX IF NOT EXISTS "shsts_pa_ft_idx" ON "SimulatedHistoricalScalarTimeSeries" ("parameterId", "forecastTime");
CREATE INDEX IF NOT EXISTS "shsts_mo_lo_pa_mt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "shsts_mo_lo_mt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_mt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "shsts_lo_pa_mt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("locationId", "parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "shsts_mo_mt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "shsts_lo_mt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("locationId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "shsts_pa_mt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "shsts_mt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("modifiedTime");
CREATE INDEX IF NOT EXISTS "shsts_tr_idx" ON "SimulatedHistoricalScalarTimeSeries" ("taskRunId");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_qu_et_lo_lf_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "localForecastTime");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_qu_et_lf_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "localForecastTime");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_qu_et_lo_ft_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "forecastTime");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_qu_et_ft_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "forecastTime");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_qu_et_lo_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_qu_et_lo_lf_en_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "localForecastTime", "ensembleId");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_qu_et_lf_en_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "localForecastTime", "ensembleId");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_qu_et_lo_ft_en_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "forecastTime", "ensembleId");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_qu_et_ft_en_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "forecastTime", "ensembleId");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_qu_et_lo_en_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "ensembleId");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_qu_et_en_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "ensembleId");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_qu_et_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId");
CREATE INDEX IF NOT EXISTS "shsts_mo_lo_pa_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId");
CREATE INDEX IF NOT EXISTS "shsts_mo_lo_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId");
CREATE INDEX IF NOT EXISTS "shsts_lo_pa_idx" ON "SimulatedHistoricalScalarTimeSeries" ("locationId", "parameterId");
CREATE INDEX IF NOT EXISTS "shsts_mo_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId");
CREATE INDEX IF NOT EXISTS "shsts_lo_idx" ON "SimulatedHistoricalScalarTimeSeries" ("locationId");
CREATE INDEX IF NOT EXISTS "shsts_pa_idx" ON "SimulatedHistoricalScalarTimeSeries" ("parameterId");
CREATE INDEX IF NOT EXISTS "shsts_ft_idx" ON "SimulatedHistoricalScalarTimeSeries" ("forecastTime");
CREATE INDEX IF NOT EXISTS "shsts_lf_idx" ON "SimulatedHistoricalScalarTimeSeries" ("localForecastTime");
CREATE INDEX IF NOT EXISTS "shsts_tr_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("taskRunId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shsts_mo_lo_pa_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shsts_mo_lo_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "locationId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shsts_lo_pa_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("locationId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shsts_mo_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shsts_lo_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("locationId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shsts_pa_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shsts_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeries" ("startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shsts_et_idx" ON "SimulatedHistoricalScalarTimeSeries" ("encodedTimeStepId");
CREATE INDEX IF NOT EXISTS "shsts_ms_idx" ON "SimulatedHistoricalScalarTimeSeries" ("sourceId");
CREATE INDEX IF NOT EXISTS "shsts_et_ft_idx" ON "SimulatedHistoricalScalarTimeSeries" ("encodedTimeStepId", "forecastTime");
CREATE INDEX IF NOT EXISTS "shsts_et_ma_ft_ms_idx" ON "SimulatedHistoricalScalarTimeSeries" ("encodedTimeStepId", "areaId", "forecastTime", "sourceId");
CREATE INDEX IF NOT EXISTS "shsts_pa_ma_ft_ms_idx" ON "SimulatedHistoricalScalarTimeSeries" ("parameterId", "areaId", "forecastTime", "sourceId");
CREATE INDEX IF NOT EXISTS "shsts_mo_ma_ft_ms_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "areaId", "forecastTime", "sourceId");
CREATE INDEX IF NOT EXISTS "shsts_ma_ft_mo_pa_et_ms_idx" ON "SimulatedHistoricalScalarTimeSeries" ("areaId", "forecastTime", "moduleInstanceId", "parameterId", "encodedTimeStepId", "sourceId");
CREATE INDEX IF NOT EXISTS "shsts_mo_pa_et_ma_ms_idx" ON "SimulatedHistoricalScalarTimeSeries" ("moduleInstanceId", "parameterId", "encodedTimeStepId", "areaId", "sourceId");
CREATE INDEX IF NOT EXISTS "shsts_co_idx" ON "SimulatedHistoricalScalarTimeSeries" ("committed");""",
		TimeSeriesTypeUtil.getTimeSeriesTypeCollection(TimeSeriesType.SCALAR_SIMULATED_HISTORICAL_STITCHED), """
CREATE TABLE IF NOT EXISTS "SimulatedHistoricalScalarTimeSeriesStitched" (
	"_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

	"timeSeriesType" TEXT NOT NULL,
	"moduleInstanceId" TEXT NOT NULL,
	"locationId" TEXT NOT NULL,
	"parameterId" TEXT NOT NULL,
	"qualifierIds" TEXT[] NOT NULL DEFAULT '{}',
	"qualifierId" TEXT NOT NULL DEFAULT '',
	"encodedTimeStepId" TEXT NOT NULL,
	"startTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"endTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"localStartTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"localEndTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"ensembleId" TEXT NOT NULL DEFAULT '',
	"ensembleMemberId" TEXT NOT NULL DEFAULT '',
	"committed" BOOLEAN NOT NULL DEFAULT false,
	"bucketSize" TEXT NOT NULL DEFAULT '',
	"bucket" BIGINT NOT NULL DEFAULT 0,

	"metaData_sourceId" TEXT NOT NULL DEFAULT '',
	"metaData_areaId" TEXT NOT NULL DEFAULT '',
	"metaData_unit" TEXT NOT NULL DEFAULT '',
	"metaData_displayUnit" TEXT NOT NULL DEFAULT '',
	"metaData_locationName" TEXT NOT NULL DEFAULT '',
	"metaData_parameterName" TEXT NOT NULL DEFAULT '',
	"metaData_parameterType" TEXT NOT NULL DEFAULT '',
	"metaData_timeStepLabel" TEXT NOT NULL DEFAULT '',
	"metaData_timeStepMinutes" INT NOT NULL DEFAULT 0,
	"metaData_localTimeZone" TEXT NOT NULL DEFAULT '',
	"metaData_archiveTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"metaData_modifiedTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"metaData_ensembleMemberIndex" INT NOT NULL DEFAULT 0,

	"timeseries_t" TIMESTAMP[] NOT NULL,
	"timeseries_lt" TIMESTAMP[] NOT NULL',
	"timeseries_v" REAL[] NOT NULL,
	"timeseries_dv" REAL[] NOT NULL,
	"timeseries_f" SMALLINT[] NOT NULL,
	"timeseries_u" TEXT[] NOT NULL,
	"timeseries_c" TEXT[] NOT NULL,
	"timeseries_fs" TEXT[] NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "shstss_mo_lo_pa_qu_et_en_em_bu_bk_key" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "ensembleId", "ensembleMemberId", "bucketSize", "bucket");
CREATE UNIQUE INDEX IF NOT EXISTS "shstss_mo_lo_pa_qu_et_en_em_st_nt_key" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "ensembleId", "ensembleMemberId", "startTime", "endTime");
CREATE UNIQUE INDEX IF NOT EXISTS "shstss_mo_lo_pa_qu_et_en_em_st_key" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "ensembleId", "ensembleMemberId", "startTime");
CREATE UNIQUE INDEX IF NOT EXISTS "shstss_mo_lo_pa_qu_et_en_em_nt_key" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "ensembleId", "ensembleMemberId", "endTime");
CREATE INDEX IF NOT EXISTS "shstss_mo_lo_pa_qu_et_en_em_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "locationId", "parameterId", "qualifierId", "encodedTimeStepId", "ensembleId", "ensembleMemberId");
CREATE INDEX IF NOT EXISTS "shstss_mo_lo_pa_mt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "locationId", "parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "shstss_mo_lo_mt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "locationId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "shstss_mo_pa_mt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "shstss_lo_pa_mt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("locationId", "parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "shstss_mo_mt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "shstss_lo_mt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("locationId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "shstss_pa_mt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("parameterId", "modifiedTime");
CREATE INDEX IF NOT EXISTS "shstss_mt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("modifiedTime");
CREATE INDEX IF NOT EXISTS "shstss_mo_pa_qu_et_lo_lst_lnt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "localStartTime", "localEndTime");
CREATE INDEX IF NOT EXISTS "shstss_mo_pa_qu_et_lst_lnt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "localStartTime", "localEndTime");
CREATE INDEX IF NOT EXISTS "shstss_mo_pa_qu_et_lo_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shstss_mo_pa_qu_et_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shstss_mo_pa_qu_et_lo_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId", "locationId");
CREATE INDEX IF NOT EXISTS "shstss_mo_pa_qu_et_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "parameterId", "qualifierId", "encodedTimeStepId");
CREATE INDEX IF NOT EXISTS "shstss_mo_lo_pa_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "locationId", "parameterId");
CREATE INDEX IF NOT EXISTS "shstss_mo_lo_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "locationId");
CREATE INDEX IF NOT EXISTS "shstss_mo_pa_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "parameterId");
CREATE INDEX IF NOT EXISTS "shstss_lo_pa_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("locationId", "parameterId");
CREATE INDEX IF NOT EXISTS "shstss_mo_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId");
CREATE INDEX IF NOT EXISTS "shstss_lo_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("locationId");
CREATE INDEX IF NOT EXISTS "shstss_pa_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("parameterId");
CREATE INDEX IF NOT EXISTS "shstss_mo_lo_pa_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "locationId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shstss_mo_lo_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "locationId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shstss_mo_pa_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shstss_lo_pa_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("locationId", "parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shstss_mo_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shstss_lo_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("locationId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shstss_pa_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("parameterId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shstss_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shstss_lst_lnt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("localStartTime", "localEndTime");
CREATE INDEX IF NOT EXISTS "shstss_et_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("encodedTimeStepId");
CREATE INDEX IF NOT EXISTS "shstss_et_st_nt_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("encodedTimeStepId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "shstss_et_ma_st_nt_ms_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("encodedTimeStepId", "areaId", "startTime", "endTime", "sourceId");
CREATE INDEX IF NOT EXISTS "shstss_pa_ma_st_nt_ms_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("parameterId", "areaId", "startTime", "endTime", "sourceId");
CREATE INDEX IF NOT EXISTS "shstss_mo_ma_st_nt_ms_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "areaId", "startTime", "endTime", "sourceId");
CREATE INDEX IF NOT EXISTS "shstss_ma_st_nt_mo_pa_et_ms_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("areaId", "startTime", "endTime", "moduleInstanceId", "parameterId", "encodedTimeStepId", "sourceId");
CREATE INDEX IF NOT EXISTS "shstss_mo_pa_et_ma_ms_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("moduleInstanceId", "parameterId", "encodedTimeStepId", "areaId", "sourceId");
CREATE INDEX IF NOT EXISTS "shstss_co_idx" ON "SimulatedHistoricalScalarTimeSeriesStitched" ("committed");""",
		Table.MigrateMetaData.toString(), """
CREATE TABLE IF NOT EXISTS "MigrateMetaData" (
	"_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

	"metaDataFileRelativePath" TEXT NOT NULL DEFAULT '',
	"metaDataFileTime" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"netcdfFiles" JSONB NOT NULL DEFAULT '[]',
	"committed" BOOLEAN NOT NULL DEFAULT false
);

CREATE UNIQUE INDEX IF NOT EXISTS "mmd_mp_key" ON "MigrateMetaData" ("metaDataFileRelativePath");
CREATE INDEX IF NOT EXISTS "mmd_nf_idx" ON "MigrateMetaData" USING GIN (("netcdfFiles"->'timeSeriesIds'));
CREATE INDEX IF NOT EXISTS "mmd_co_idx" ON "MigrateMetaData" ("committed");""",
		Table.MigrateLog.toString(), """
CREATE TABLE IF NOT EXISTS "MigrateLog" (
	"_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	
	"date" TIMESTAMP NOT NULL DEFAULT '1800-01-01 00:00:00',
	"errorCategory" TEXT NOT NULL DEFAULT '',
	"data" JSONB NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS "ml_da_idx" ON "MigrateLog" ("date");
CREATE INDEX IF NOT EXISTS "ml_ec_idx" ON "MigrateLog" ("errorCategory");""", 
		Table.BucketSize.toString(), """
CREATE TABLE IF NOT EXISTS "BucketSize" (
	"_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

	"bucketCollection" TEXT NOT NULL DEFAULT '',
	"bucketKey" TEXT NOT NULL DEFAULT '',
	"bucketSize" TEXT NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX IF NOT EXISTS "bs_bc_bk_key" ON "BucketSize" ("bucketCollection", "bucketKey");"""
	);
}
