name: archive-verification
on:
  push:
    branches: [ master ]
    paths:
      - 'archive-verification/archive-verification/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'archive-verification/archive-verification/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: corretto
    - run: mvn -B package --file archive-verification/archive-verification/pom.xml
    - uses: actions/upload-artifact@v4
      with:
        name: archive-verification
        path: ./archive-verification/archive-verification/target/verification.war
