name: archive-database
on:
  push:
    branches: [ master ]
    paths: 
      - 'archive-database/archive-database/**'
  pull_request:
    branches: [ master ]
    paths: 
      - 'archive-database/archive-database/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: corretto
    - run: mvn -B package --file archive-database/archive-database/pom.xml
    - uses: actions/upload-artifact@v4
      with:
        name: archive-database
        path: ./archive-database/archive-database/target/archive-database*.jar
