# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: publish and test plugin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file archive-database/pom.xml
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mongodb
        path: |
          ./archive-database/target/archive-database*.jar
          ./archive-database/target/Delft_Archive_Server.jar
