name: publish and test plugin

on:
  push:
    branches: [ "FEWS-202202NA" ]
  pull_request:
    branches: [ "FEWS-202202NA" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: corretto
    - name: Build with Maven
      run: mvn -B package --file archive-database/pom.xml
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mongodb
        path: ./archive-database/target/archive-database*.jar
