name: Database
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    paths:
      - 'archive-database/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@latest
    - uses: actions/setup-java@latest
      with:
        java-version: 17
        distribution: corretto
    - run: mvn -B package --file archive-database/pom.xml
    - uses: actions/upload-artifact@latest
      with:
        path: ./archive-database/target/archive-database*.jar
