name: publish and test war

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: corretto
    - name: Build with Maven
      run: mvn -B package --file archive-verification/web/pom.xml
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: verification
        path: ./archive-verification/web/target/verification.war
