name: Verification
on:
  push:
    branches: [ FEWS-202202NA ]
  pull_request:
    branches: [ FEWS-202202NA ]
  workflow_dispatch:
    paths:
      - 'archive-verification/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: corretto
    - run: mvn -B package --file archive-verification/web/pom.xml
    - uses: actions/upload-artifact@v4
      with:
        path: ./archive-verification/web/target/verification.war
